"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { Download, Share2, Copy, FileText, Link2, Check, Mail, BarChart3, FileDown } from "lucide-react"
import { toast } from "sonner"
import type { AnalysisResult } from "@/app/page"
import { downloadPDFReport } from "@/lib/generate-pdf"

interface ExportReportProps {
  results: AnalysisResult
  sourceUrl?: string
}

export function ExportReport({ results, sourceUrl }: ExportReportProps) {
  const [copied, setCopied] = useState(false)
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false)

  const handleDownloadPDF = async () => {
    try {
      setIsGeneratingPDF(true)
      toast.info("Generating professional PDF report...")
      
      await downloadPDFReport(
        results,
        sourceUrl,
        new Date(),
        `veritas-report-${Date.now()}.pdf`
      )
      
      toast.success("PDF report downloaded successfully")
    } catch (error) {
      console.error("PDF generation error:", error)
      toast.error("Failed to generate PDF report")
    } finally {
      setIsGeneratingPDF(false)
    }
  }

  const generateReportText = () => {
    const timestamp = new Date().toLocaleString()
    const verificationRate =
      results.claims.length > 0
        ? Math.round((results.claims.filter((c) => c.status === "verified").length / results.claims.length) * 100)
        : 0

    return `VERITAS AI - NEWS AUTHENTICITY REPORT
Generated: ${timestamp}
Powered by: Gemini 1.5 Flash AI, Tavily Search, Jina AI, Firecrawl
${sourceUrl ? `Source: ${sourceUrl}` : ""}

VERDICT: ${results.verdict}
CONFIDENCE: ${results.confidence}%
VERIFICATION RATE: ${verificationRate}%

EXECUTIVE SUMMARY:
${results.summary}

DETAILED CLAIM ANALYSIS:
${results.claims
  .map(
    (claim, i) =>
      `${i + 1}. CLAIM: ${claim.text}
   STATUS: ${claim.status.toUpperCase()}
   ANALYSIS: ${claim.explanation}`,
  )
  .join("\n\n")}

AI REASONING:
${results.reasoning}

VERIFIED SOURCES:
${results.sources
  .map(
    (source, i) =>
      `${i + 1}. ${source.title}
   URL: ${source.url}`,
  )
  .join("\n\n")}

METHODOLOGY:
- Multi-tier content extraction (Jina AI, Firecrawl, Article Extractor)
- Real-time web search and fact-checking (Tavily AI)
- AI-powered claim analysis (Google Gemini 1.5 Flash)
- Cross-referencing with authoritative news sources

DISCLAIMER:
This analysis was generated using Veritas AI's advanced fact-checking system
combining multiple AI tools and web search. Results should be considered as
part of a comprehensive fact-checking process.

---
Report generated by Veritas AI - News Authenticity Analyzer
Tools: Gemini 1.5 Flash | Tavily Search | Jina AI | Firecrawl | ${new Date().getFullYear()}
`
  }

  const generateDetailedReport = () => {
    const timestamp = new Date().toLocaleString()
    const verificationRate =
      results.claims.length > 0
        ? Math.round((results.claims.filter((c) => c.status === "verified").length / results.claims.length) * 100)
        : 0

    const verifiedClaims = results.claims.filter((c) => c.status === "verified").length
    const contradictedClaims = results.claims.filter((c) => c.status === "contradicted").length
    const unverifiedClaims = results.claims.filter((c) => c.status === "unverified").length

    return `<!DOCTYPE html>
<html>
<head>
    <title>Veritas AI Analysis Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
        .header { border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 30px; }
        .verdict { background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0; }
        .claims { margin: 30px 0; }
        .claim { margin: 20px 0; padding: 15px; border-left: 4px solid #ddd; }
        .verified { border-left-color: #22c55e; }
        .contradicted { border-left-color: #ef4444; }
        .unverified { border-left-color: #f59e0b; }
        .sources { margin: 30px 0; }
        .source { margin: 10px 0; padding: 10px; background: #f9f9f9; }
        .stats { display: flex; gap: 20px; margin: 20px 0; }
        .stat { text-align: center; padding: 15px; background: #f0f0f0; border-radius: 8px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Veritas AI - News Authenticity Report</h1>
        <p><strong>Generated:</strong> ${timestamp}</p>
        <p><strong>Powered by:</strong> Gemini 1.5 Flash, Tavily Search, Jina AI, Firecrawl</p>
        ${sourceUrl ? `<p><strong>Source:</strong> <a href="${sourceUrl}">${sourceUrl}</a></p>` : ""}
    </div>

    <div class="verdict">
        <h2>Analysis Verdict</h2>
        <p><strong>Result:</strong> ${results.verdict}</p>
        <p><strong>Confidence Level:</strong> ${results.confidence}%</p>
        <p><strong>Verification Rate:</strong> ${verificationRate}%</p>
    </div>

    <div class="stats">
        <div class="stat">
            <h3>${verifiedClaims}</h3>
            <p>Verified Claims</p>
        </div>
        <div class="stat">
            <h3>${contradictedClaims}</h3>
            <p>Contradicted Claims</p>
        </div>
        <div class="stat">
            <h3>${unverifiedClaims}</h3>
            <p>Unverified Claims</p>
        </div>
    </div>

    <h2>Executive Summary</h2>
    <p>${results.summary}</p>

    <div class="claims">
        <h2>Detailed Claim Analysis</h2>
        ${results.claims
          .map(
            (claim, i) =>
              `<div class="claim ${claim.status}">
                <h3>Claim ${i + 1}</h3>
                <p><strong>Statement:</strong> ${claim.text}</p>
                <p><strong>Status:</strong> ${claim.status.toUpperCase()}</p>
                <p><strong>Analysis:</strong> ${claim.explanation}</p>
              </div>`,
          )
          .join("")}
    </div>

    <h2>AI Reasoning</h2>
    <p>${results.reasoning}</p>

    <div class="sources">
        <h2>Verified Sources</h2>
        ${results.sources
          .map(
            (source, i) =>
              `<div class="source">
                <h4>${i + 1}. ${source.title}</h4>
                <p><a href="${source.url}">${source.url}</a></p>
              </div>`,
          )
          .join("")}
    </div>

    <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666;">
        <p>This analysis was generated using Veritas AI's multi-tier fact-checking system with AI-powered claim analysis and web search verification.</p>
        <p>Report generated by Veritas AI - News Authenticity Analyzer | Tools: Gemini 1.5 Flash, Tavily AI, Jina AI, Firecrawl | ${new Date().getFullYear()}</p>
    </div>
</body>
</html>`
  }

  const handleCopyReport = async () => {
    try {
      await navigator.clipboard.writeText(generateReportText())
      setCopied(true)
      toast.success("Report copied to clipboard")
      setTimeout(() => setCopied(false), 2000)
    } catch (error) {
      toast.error("Failed to copy report")
    }
  }

  const handleDownloadReport = () => {
    const reportText = generateReportText()
    const blob = new Blob([reportText], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `veritas-ai-report-${Date.now()}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    toast.success("Report downloaded successfully")
  }

  const handleDownloadHTMLReport = () => {
    const reportHTML = generateDetailedReport()
    const blob = new Blob([reportHTML], { type: "text/html" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `veritas-ai-report-${Date.now()}.html`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    toast.success("HTML report downloaded successfully")
  }

  const handleEmailReport = () => {
    const subject = encodeURIComponent(`Veritas AI Analysis: ${results.verdict}`)
    const body = encodeURIComponent(`I've analyzed a news article using Veritas AI with advanced AI and fact-checking capabilities.

Verdict: ${results.verdict}
Confidence: ${results.confidence}%

${results.summary}

${sourceUrl ? `Source: ${sourceUrl}` : ""}

Analyzed using: Gemini 1.5 Flash, Tavily Search, Jina AI, Firecrawl
Full report attached.`)

    window.location.href = `mailto:?subject=${subject}&body=${body}`
  }

  const handleShareUrl = async () => {
    try {
      if (sourceUrl) {
        await navigator.clipboard.writeText(sourceUrl)
        toast.success("Source URL copied to clipboard")
      } else {
        toast.error("No source URL available")
      }
    } catch (error) {
      toast.error("Failed to copy URL")
    }
  }

  const handleShareReport = async () => {
    const reportText = generateReportText()
    
    const shareData = {
      title: `Veritas AI Analysis: ${results.verdict}`,
      text: reportText,
    }

    if (navigator.share) {
      try {
        await navigator.share(shareData)
        toast.success("Report shared successfully")
      } catch (error) {
        // Fallback to clipboard if share fails
        try {
          await navigator.clipboard.writeText(reportText)
          toast.success("Report copied to clipboard (share not supported)")
        } catch (clipError) {
          toast.error("Failed to share report")
        }
      }
    } else {
      // Fallback to clipboard if Web Share API not available
      try {
        await navigator.clipboard.writeText(reportText)
        toast.success("Report copied to clipboard")
      } catch (error) {
        toast.error("Failed to copy report")
      }
    }
  }

  return (
    <Card className="border-slate-200/50 dark:border-slate-700/50 bg-gradient-to-br from-white to-slate-50/50 dark:from-slate-900 dark:to-slate-900/50 backdrop-blur shadow-xl">
      <CardContent className="p-4 sm:p-6">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-blue-100 dark:bg-blue-900/30">
              <Download className="h-5 w-5 text-blue-600 dark:text-blue-400" />
            </div>
            <div>
              <h3 className="text-base sm:text-lg font-semibold text-slate-900 dark:text-slate-100">Export Analysis Report</h3>
              <p className="text-xs sm:text-sm text-slate-600 dark:text-slate-400">
                Download or share verification results
              </p>
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-2 w-full sm:w-auto">
            <Button
              variant="outline"
              size="sm"
              onClick={handleCopyReport}
              className="flex items-center gap-2 bg-white dark:bg-slate-800 hover:bg-slate-50 dark:hover:bg-slate-700 border-slate-200 dark:border-slate-700 text-xs sm:text-sm flex-1 sm:flex-none"
            >
              {copied ? <Check className="h-3 w-3 sm:h-4 sm:w-4 text-green-600" /> : <Copy className="h-3 w-3 sm:h-4 sm:w-4" />}
              {copied ? "Copied!" : "Copy"}
            </Button>

            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button
                  variant="outline"
                  size="sm"
                  className="flex items-center gap-2 bg-white dark:bg-slate-800 hover:bg-slate-50 dark:hover:bg-slate-700 border-slate-200 dark:border-slate-700 text-xs sm:text-sm flex-1 sm:flex-none"
                >
                  <Download className="h-3 w-3 sm:h-4 sm:w-4" />
                  Export
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="start" sideOffset={6} className="w-56 bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700">
                <DropdownMenuItem onClick={handleDownloadPDF} disabled={isGeneratingPDF} className="cursor-pointer">
                  <FileDown className="h-4 w-4 mr-2 text-red-600 dark:text-red-400" />
                  <span className="flex-1">{isGeneratingPDF ? 'Generating PDF...' : 'Download as PDF'}</span>
                </DropdownMenuItem>
                <DropdownMenuItem onClick={handleDownloadReport} className="cursor-pointer">
                  <FileText className="h-4 w-4 mr-2 text-blue-600 dark:text-blue-400" />
                  <span>Download as Text</span>
                </DropdownMenuItem>
                <DropdownMenuItem onClick={handleDownloadHTMLReport} className="cursor-pointer">
                  <BarChart3 className="h-4 w-4 mr-2 text-purple-600 dark:text-purple-400" />
                  <span>Download as HTML</span>
                </DropdownMenuItem>
                <DropdownMenuItem onClick={handleEmailReport} className="cursor-pointer">
                  <Mail className="h-4 w-4 mr-2 text-green-600 dark:text-green-400" />
                  <span>Share via Email</span>
                </DropdownMenuItem>
                {sourceUrl && (
                  <DropdownMenuItem onClick={handleShareUrl} className="cursor-pointer">
                    <Link2 className="h-4 w-4 mr-2 text-cyan-600 dark:text-cyan-400" />
                    <span>Copy Source URL</span>
                  </DropdownMenuItem>
                )}
              </DropdownMenuContent>
            </DropdownMenu>

            <Button
              variant="default"
              size="sm"
              onClick={handleShareReport}
              className="flex items-center gap-2 text-xs sm:text-sm bg-gradient-to-r from-blue-600 to-cyan-600 hover:from-blue-700 hover:to-cyan-700 shadow-lg flex-1 sm:flex-none"
            >
              <Share2 className="h-3 w-3 sm:h-4 sm:w-4" />
              Share
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}